### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by mirgee** [priitj/grils-t#1]
Can you please specify what Python version did you use to run? I tried 2.7 and 3.7, both with errors. Thanks!

**Comment by priitj** [comment]
Hi,

2.7 should be a good starting point, since I used mostly 2.7.5. I've never tested Python 3.

Before running, the .pyx modules should be compiled though. Did that work?

**Comment by mirgee** [comment]
Yes, I had to modify wireformat.py a bit (implement custom cmp method), but it did.

Now when I run 
`mpirun python2.7 ./loader.py op dist.gop 10 2000 logfile`
I get "no module named op" on loader.py. With python3.7, it seems to get further, but complains on stuff like "'map' has no len()"...

**Comment by mirgee** [comment]
OK, I had to implement custom cmp method in wireformat.py, compile with and install dependencies for and run with python2.7. It runs without error now, but the logfile is empty?

**Comment by priitj** [comment]
What error did you get with built in `cmp()`? That sounds a bit suspicious.

As for the missing output, perhaps `mpirun` defaults to 1 copy of the program? In that case it will not actually do anything. You need at least 2 copies running, the first one will always be the monitor and the rest are workers. You can try `mpirun -n 2 ...`.

**Comment by mirgee** [comment]
With `mpirun -n 2`, it works now! Thank you!
