### ISSUE TITLE
Distance limit

### ISSUE THREAD

**Issue by mirgee** [priitj/grils-t#2]
Does the solver support distance limit for the OP?

**Comment by priitj** [comment]
Yes, of course. There are no units so you can think of cost as time or distance or whatever you like.

It expects an input file in a specific format for the OP and the distance limit is one field in that format.

See the documentation for the benchmark data for more information.

**Comment by mirgee** [comment]
Hi, thanks for reply. I have downloaded the test instances you linked in readme from http://josilber.scripts.mit.edu/gop.zip, where the [format](https://github.com/priitj/grils-t/files/1202422/README.txt) doesn't include distance limit, only starting and ending nodes. The [OP format](https://github.com/priitj/grils-t/files/1202421/OP_format.txt) which includes Tmax is a little different from the format your readme suggests to run, it seems. 

Also, your solver seems to expect the distance matrix format without Tmax and throws and error when I try to run `mpirun python ./loader.py op coord.gop 10 2000 logfile` in the coordinate format with Tmax.

**Comment by mirgee** [comment]
And strangely, even when I enter [custom problem](https://github.com/priitj/grils-t/files/1202467/dist.txt) in the expected format, I get empty output file even when run with `mpirun -n 2`, which works for test instances. Do you have any idea why this could be, please?

**Comment by priitj** [comment]
My bad, in case of OP the distance limit is in `opdata.py`, not in the input file.

**Comment by mirgee** [comment]
Awsome, thank you!
